defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: cc9bf9b0-89fa-4be5-9f02-bcf4fd7f34f1 # Default
handle: marketNews
maxAuthors: 1
name: 'Market News'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  909be81a-6639-4abb-b51f-bd2fb0c1dd98: # Olivia
    enabledByDefault: true
    hasUrls: true
    template: _news/_entry.twig
    uriFormat: 'austin-housing-market-news/{slug}'
type: channel
